kind: Service
apiVersion: v1
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31000
  selector:
    app: grafana
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:4.1.1
          ports: 
            - containerPort: 3000
