apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
    scrape_configs:
    - job_name: jenkins
      metrics_path: '/prometheus'
      scrape_interval: 5s
      static_configs:
      - targets:
        - jenkins:8080
