kind: Service
apiVersion: v1
metadata:
  name: pushgateway
spec:
  type: NodePort
  ports:
    - port: 9091
      nodePort: 31091
  selector:
    app: pushgateway
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pushgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          imagePullPolicy: Always
          image: prom/pushgateway:v0.3.1
          ports:
            - containerPort: 9091
